package com.schoollog.attendance.debugqa.presentation

import com.schoollog.attendance.core.common.RecognitionMode
import com.schoollog.attendance.debugqa.domain.CalibrationFaceCondition
import com.schoollog.attendance.debugqa.domain.CalibrationLightingCondition

data class RecognitionQaUiState(
    val schoolId: String = "",
    val enrolledStudentCount: Int = 0,
    val modelVersion: String = "--",
    val inputWidth: Int = 0,
    val inputHeight: Int = 0,
    val embeddingSize: Int = 0,
    val recognitionMode: RecognitionMode = RecognitionMode.Strict,
    val thresholdAcceptance: Float = 0.86f,
    val thresholdMargin: Float = 0.04f,
    val sessionId: String = "",
    val testerName: String = "",
    val sessionNotes: String = "",
    val expectedStudentId: String = "",
    val lightingCondition: CalibrationLightingCondition = CalibrationLightingCondition.NORMAL,
    val faceCondition: CalibrationFaceCondition = CalibrationFaceCondition.NORMAL,
    val lastTop1StudentId: String? = null,
    val lastTop1Score: Float? = null,
    val lastTop2StudentId: String? = null,
    val lastTop2Score: Float? = null,
    val lastTop3StudentId: String? = null,
    val lastTop3Score: Float? = null,
    val lastTop1Top2Margin: Float? = null,
    val lastDecision: String = "--",
    val lastCalibrationFailureReason: String = "None",
    val lastTotalDecisionTimeMs: Double = 0.0,
    val genuineAccepted: Int = 0,
    val genuineRejected: Int = 0,
    val wrongAccepted: Int = 0,
    val ambiguousRejected: Int = 0,
    val lowConfidenceRejected: Int = 0,
    val averageDecisionTimeMs: Double = 0.0,
    val averageMatchingMillis: Double = 0.0,
    val lastTopMatchScores: List<Float> = emptyList(),
    val lastFailureReason: String = "None",
    val modelFound: Boolean? = null,
    val modelLoaded: Boolean? = null,
    val modelSmokeTestPassed: Boolean? = null,
    val lastModelInferenceMillis: Double? = null,
    val inputChannels: Int = 0,
    val inputDataType: String = "--",
    val actualInputShape: String = "--",
    val actualOutputShape: String = "--",
    val actualOutputDataType: String = "--",
    val lastModelError: String? = null,
    val isRunningModelSmokeTest: Boolean = false,
    val statusMessage: String? = null,
    val cacheVersion: Long = 0L,
    val isLoading: Boolean = false,
)
